#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2019 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited
#
# This provides incremental updates to existing packages in EasyApache4.
package scl_phalcon::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

unless ( caller() ) {
    ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum );
}

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my $res = $http->get("https://github.com/phalcon/cphalcon/releases");
    if ( !$res->{success} ) {
        die "Could not GET phalcon dist page ($res->{status} $res->{reason})\n";
    }

    my @phalcon = sort { $b <=> $a } ( $res->{content} =~ m{href="/phalcon/cphalcon/tree/v3\.([0-9]+\.[0-9]+)"}g );
    if ( !@phalcon ) {
        die "Could not find phalcon versions\n";
    }

    # To make sure the signatures are valid we will NOT be downloading a
    # tarball.  We will instead git clone, git checkout, git verify-commit
    # after making sure the gpg keys are in place.
    # so the actual tarball will be pulled from the git repo, not downloaded

    my $version = "3\.$phalcon[0]";
    my $name    = "v$version.tar.gz";
    my $url     = "https://github.com/phalcon/cphalcon.git";

    return ( $version, $url, $name, {
        git_dir => 'cphalcon',
        tarball_main_dir => 'cphalcon_' . $version,
        tag => 'v' . $version,
    });
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    $hr->{tarball}{sum}{type} = "github_gpg_signed_commit";
    $hr->{tarball}{sum}{gpg}  = {
        key_url        => 'https://keybase.io/klay/pgp_keys.asc',
        key_email      => 'sadhooklay@gmail.com',
    };

    return;
}
